---
- name: Install Netbox
  hosts: netbox
  become: yes
  vars:
    netbox_version: "3.4.3"
    netbox_url: "https://github.com/netbox-community/netbox/archive/refs/tags/v{{ netbox_version }}.tar.gz"
  tasks:
    - name: Install dependencies
      apt:
        name:
          - build-essential
          - libssl-dev
          - libffi-dev
          - python3-dev
          - python3-pip
          - python3-setuptools
        state: present

    - name: Install virtualenv
      pip:
        name: virtualenv
        state: present

    - name: Create virtual environment
      shell: |
        virtualenv /opt/netbox/venv
        source /opt/netbox/venv/bin/activate
        pip install -U pip setuptools

    - name: Download Netbox
      unarchive:
        src: "{{ netbox_url }}"
        dest: /opt/netbox
        remote_src: yes

    - name: Install Netbox
      pip:
        virtualenv: "/opt/netbox/venv"
        requirements: "/opt/netbox/netbox-{{ netbox_version }}/requirements.txt"

    - name: Create configuration file
      copy:
        src: netbox.env
        dest: /opt/netbox/netbox-{{ netbox_version }}/netbox/netbox.env
        owner: root
        group: root
        mode: 0644

    - name: Collect static files
      shell: |
        source /opt/netbox/venv/bin/activate
        cd /opt/netbox/netbox-{{ netbox_version }}
        python manage.py collectstatic --noinput

    - name: Migrate database
      shell: |
        source /opt/netbox/venv/bin/activate
        cd /opt/netbox/netbox-{{ netbox_version }}
        python manage.py migrate

    - name: Create admin user
      shell: |
        source /opt/netbox/venv/bin/activate
        cd /opt/netbox/netbox-{{ netbox_version }}
        echo "from django.contrib.auth import get_user_model; User = get_user_model(); User.objects.create_superuser('admin', 'admin@example.com', 'password')" | python manage.py shell
