---
- name: Install Jenkins
  hosts: jenkins
  become: yes
  tasks:
  - name: install dependencies
    apt:
      name:
        - openjdk-11-jdk
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg2
      state: present

  - name: add Jenkins repository key
    apt_key:
      url: https://pkg.jenkins.io/debian/jenkins.io.key
      state: present

  - name: add Jenkins repository
    lineinfile:
      dest: /etc/apt/sources.list.d/jenkins.list
      line: deb https://pkg.jenkins.io/debian binary/
      state: present

  - name: install Jenkins
    apt:
      name: jenkins
      state: present

  - name: start Jenkins service
    service:
      name: jenkins
      state: started
