- name: Install Nexus OSS with Nginx HTTPS and remote source for SSL certificates
  hosts: all
  gather_facts: yes
  vars:
    nexus_version: latest
    nexus_edition: oss
    nexus_repo: https://download.sonatype.com/nexus/oss
    nexus_download_url: "{{ nexus_repo }}/nexus-{{ nexus_version }}-{{ nexus_edition }}-unix.tar.gz"
    nexus_install_dir: /opt/nexus
    ssl_certificate_path: /path/to/ssl/certificate
    ssl_certificate_key_path: /path/to/ssl/certificate_key
    nexus_hostname: example.com
  
  tasks:
    - name: Install required packages
      become: yes
      package:
        name:
          - openjdk-8-jdk
          - nginx
      state: present
      
    - name: Download Nexus OSS
      become: yes
      get_url:
        url: "{{ nexus_download_url }}"
        dest: /tmp/nexus.tar.gz
        
    - name: Extract Nexus OSS
      become: yes
      command: tar xzf /tmp/nexus.tar.gz -C /opt
      args:
        creates: "{{ nexus_install_dir }}/nexus-{{ nexus_version }}-{{ nexus_edition }}"
        
    - name: Copy SSL certificates from remote source
      become: yes
      copy:
        src: "{{ item }}"
        dest: "/path/to/destination"
      with_items:
        - "{{ ssl_certificate_path }}"
        - "{{ ssl_certificate_key_path }}"
        
    - name: Configure Nginx
      become: yes
      template:
        src: templates/nginx.conf.j2
        dest: /etc/nginx/sites-available/default
      vars:
        nexus_hostname: "{{ nexus_hostname }}"
        ssl_certificate_path: "{{ ssl_certificate_path }}"
        ssl_certificate_key_path: "{{ ssl_certificate_key_path }}"
        
    - name: Start Nexus
      become: yes
      command: "{{ nexus_install_dir }}/nexus-{{ nexus_version }}-{{ nexus_edition }}/bin/nexus start"
      
    - name: Start Nginx
      become: yes
      service:
        name: nginx
        state: started
